/*
 * Raj Shah
 * ICS 4UE
 * August 2, 2023
 * Program description: This program will act as a calculator, it will add,
 * subtract, multiply divide, take the sqrt, and raise numbers to the 2nd and 3rd
 * power. It can also do summation and products in given intervals.
 */

/**
 *
 * @author Raj
 */

import java.lang.Math; // import math method
public class U1A4 extends javax.swing.JFrame {

    /**
     * Creates new form U1A4
     */
    public U1A4() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jDialog2 = new javax.swing.JDialog();
        jDialog3 = new javax.swing.JDialog();
        jFrame1 = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        myTextField = new javax.swing.JTextField();
        plusBtn = new javax.swing.JButton();
        minusBtn = new javax.swing.JButton();
        javax.swing.JButton multiplyBtn = new javax.swing.JButton();
        javax.swing.JButton divideBtn = new javax.swing.JButton();
        javax.swing.JButton sqrtBtn = new javax.swing.JButton();
        javax.swing.JButton squaredBtn = new javax.swing.JButton();
        javax.swing.JButton cubedBtn = new javax.swing.JButton();
        outputLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userNum1 = new javax.swing.JTextField();
        userNum2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        userNum3 = new javax.swing.JTextField();
        myComboBox = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        upperBound = new javax.swing.JTextField();
        lowerBound = new javax.swing.JTextField();
        javax.swing.JButton calculateSumOrProduct = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        javax.swing.JButton exitBtn = new javax.swing.JButton();
        javax.swing.JButton absBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Basic Calculator");

        jLabel1.setFont(new java.awt.Font("Hiragino Sans", 1, 36)); // NOI18N
        jLabel1.setText("Calculator");

        myTextField.setEditable(false);
        myTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        myTextField.setForeground(new java.awt.Color(255, 0, 0));
        myTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        plusBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        plusBtn.setText("+");
        plusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusBtnActionPerformed(evt);
            }
        });

        minusBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        minusBtn.setText("-");
        minusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusBtnActionPerformed(evt);
            }
        });

        multiplyBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        multiplyBtn.setText("×");
        multiplyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyBtnActionPerformed(evt);
            }
        });

        divideBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        divideBtn.setText("÷");
        divideBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideBtnActionPerformed(evt);
            }
        });

        sqrtBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        sqrtBtn.setText("√");
        sqrtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sqrtBtnActionPerformed(evt);
            }
        });

        squaredBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        squaredBtn.setText("x^2");
        squaredBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squaredBtnActionPerformed(evt);
            }
        });

        cubedBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        cubedBtn.setText("x^3");
        cubedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubedBtnActionPerformed(evt);
            }
        });

        outputLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        outputLabel.setForeground(new java.awt.Color(255, 0, 0));
        outputLabel.setText("Output:");

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setText("Enter 2 numbers: ");

        userNum1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        userNum2.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setText("Enter a number: ");

        userNum3.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        myComboBox.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        myComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sum of all integers in given interval", "Product of all integers in given interval" }));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel4.setText("Lower bound:");

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel5.setText("Upper bound:");

        upperBound.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        lowerBound.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N

        calculateSumOrProduct.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        calculateSumOrProduct.setText("Calculate");
        calculateSumOrProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateSumOrProductActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        absBtn.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        absBtn.setText("Abs");
        absBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                absBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sqrtBtn)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(userNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(plusBtn)
                                            .addGap(18, 18, 18)
                                            .addComponent(minusBtn)
                                            .addGap(18, 18, 18)
                                            .addComponent(multiplyBtn)
                                            .addGap(18, 18, 18)
                                            .addComponent(divideBtn))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(userNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(userNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(squaredBtn)
                        .addGap(18, 18, 18)
                        .addComponent(cubedBtn)
                        .addGap(18, 18, 18)
                        .addComponent(absBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(myComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel4)
                                .addGap(49, 49, 49)
                                .addComponent(lowerBound, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(upperBound, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67)
                        .addComponent(calculateSumOrProduct))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(myTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(55, 55, 55)
                    .addComponent(jLabel5)
                    .addContainerGap(498, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plusBtn)
                    .addComponent(minusBtn)
                    .addComponent(multiplyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(divideBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(userNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sqrtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(squaredBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cubedBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(absBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(myComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(upperBound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calculateSumOrProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lowerBound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(myTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(657, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(304, 304, 304)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // add method
    private static double add(double x, double y) {
        return x + y;
    }
    
    // subtract method
    private static double subtract(double x, double y) {
        return x - y;
    }
    
    // multiply method
    private static double multiply(double x, double y) {
        return x * y;
    }
    
    // divide method
    private static double divide(double x, double y) {
        return x / y;
    }
    
    // sqrt method
    private static double sqrt(double x) {
        return Math.sqrt(x);
    }
    
    // x^2 method
    private static double squared(double x) {
        return Math.pow(x, 2);
    }
    
    // x^3 method
    private static double cubed(double x) {
        return Math.pow(x, 3);
    }
    
    // abs method
    private static double abs(double x) {
        return Math.abs(x);
    }
    
    private void plusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusBtnActionPerformed
        // TODO add your handling code here:
        String amountIn1 = userNum1.getText(); 
        String amountIn2 = userNum2.getText(); // get user input
        
        try { // check if user input is correct
           double num1 = Double.parseDouble(amountIn1); // convert to double
           double num2 = Double.parseDouble(amountIn2); // convert to double
           
           double sum = add(num1, num2); // perform operation
           String sum1 = String.valueOf(sum); // convert to string
           myTextField.setText(sum1);
        }
        
        catch (Exception e){
            myTextField.setText("Incorrect Input"); // inform user about incorrect input
        }
    }//GEN-LAST:event_plusBtnActionPerformed

    private void minusBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusBtnActionPerformed
        // TODO add your handling code here:
        String amountIn1 = userNum1.getText(); 
        String amountIn2 = userNum2.getText(); // get user input
        
        try { // check if user input is correct
           double num1 = Double.parseDouble(amountIn1); // convert to double
           double num2 = Double.parseDouble(amountIn2); // convert to double
           
           double difference = subtract(num1, num2); // perform operation
           String difference1 = String.valueOf(difference); // convert to string
           myTextField.setText(difference1);
        }
        
        catch (Exception e){
            myTextField.setText("Incorrect Input"); // inform user about incorrect input
        }
    }//GEN-LAST:event_minusBtnActionPerformed

    private void multiplyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyBtnActionPerformed
        // TODO add your handling code here:
        String amountIn1 = userNum1.getText(); 
        String amountIn2 = userNum2.getText(); // get user input
        
        try { // check if user input is correct
           double num1 = Double.parseDouble(amountIn1); // convert to double
           double num2 = Double.parseDouble(amountIn2); // convert to double
           
           double product = multiply(num1, num2); // perform operation
           String product1 = String.valueOf(product); // convert to string
           myTextField.setText(product1);
        }
        
        catch (Exception e){
            myTextField.setText("Incorrect Input"); // inform user about incorrect input
        }
    }//GEN-LAST:event_multiplyBtnActionPerformed

    private void divideBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideBtnActionPerformed
        // TODO add your handling code here:
        String amountIn1 = userNum1.getText(); 
        String amountIn2 = userNum2.getText(); // get user input
        
        try { // check if user input is correct
           double num1 = Double.parseDouble(amountIn1); // convert to double
           double num2 = Double.parseDouble(amountIn2); // convert to double
           
           if (num2 == 0) {
               myTextField.setText("Division by Zero!"); // inform user about division by 0
           }
           else {
           double quotient = divide(num1, num2); // perform operation
           String quotient1 = String.valueOf(quotient); // convert to string
           myTextField.setText(quotient1);
           }
        }
        
        catch (Exception e){
            myTextField.setText("Incorrect Input"); // inform user about incorrect input
        }
    }//GEN-LAST:event_divideBtnActionPerformed

    private void sqrtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sqrtBtnActionPerformed
        // TODO add your handling code here:
        String amountIn3 = userNum3.getText(); // get user input
        
        try { // check if user input is correct
           double num3 = Double.parseDouble(amountIn3); // convert to double
           
           double sqrt = sqrt(num3); // perform operation
           String sqrt1 = String.valueOf(sqrt); // convert to string
           myTextField.setText(sqrt1);
        }
        
        catch (Exception e){
            myTextField.setText("Incorrect Input"); // inform user about incorrect input
        }
    }//GEN-LAST:event_sqrtBtnActionPerformed

    private void squaredBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squaredBtnActionPerformed
        // TODO add your handling code here:
        String amountIn3 = userNum3.getText(); // get user input
        
        try { // check if user input is correct
           double num3 = Double.parseDouble(amountIn3); // convert to double
           
           double squared = squared(num3); // perform operation
           String squared1 = String.valueOf(squared); // convert to string
           myTextField.setText(squared1);
        }
        
        catch (Exception e){
            myTextField.setText("Incorrect Input"); // inform user about incorrect input
        }
    }//GEN-LAST:event_squaredBtnActionPerformed

    private void cubedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubedBtnActionPerformed
        // TODO add your handling code here:
        String amountIn3 = userNum3.getText(); // get user input
        
        try { // check if user input is correct
           double num3 = Double.parseDouble(amountIn3); // convert to double
           
           double cubed = cubed(num3); // perform operation
           String cubed1 = String.valueOf(cubed); // convert to string
           myTextField.setText(cubed1);
        }
        
        catch (Exception e){
            myTextField.setText("Incorrect Input"); // inform user about incorrect input
        }
    }//GEN-LAST:event_cubedBtnActionPerformed

    private void absBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_absBtnActionPerformed
        // TODO add your handling code here:
        String amountIn3 = userNum3.getText(); // get user input
        
        try { // check if user input is correct
           double num3 = Double.parseDouble(amountIn3); // convert to double
           
           double abs = abs(num3); // perform operation
           String abs1 = String.valueOf(abs); // convert to string
           myTextField.setText(abs1);
        }
        
        catch (Exception e){
            myTextField.setText("Incorrect Input"); // inform user about incorrect input
        }
    }//GEN-LAST:event_absBtnActionPerformed
        
    private void calculateSumOrProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateSumOrProductActionPerformed
        // TODO add your handling code here:
        String amountIn4 = upperBound.getText(); // get user input
        String amountIn5 = lowerBound.getText(); // get user input
        String text = (String)myComboBox.getSelectedItem(); // get user input
        
        try { // check if user input is correct
           int upper = Integer.parseInt(amountIn4); // convert to int
           int lower = Integer.parseInt(amountIn5); 
           
           if (upper < lower || upper < 0 || lower < 0) {
               myTextField.setText("Incorrect Input");
           } else {
               
               if (text.equals("Sum of all integers in given interval")){
                    
                   // add numbers from lower interval to upper interval
                   int Sum = 0;
                   for (int i = lower; i <= upper; i++) { 
                        Sum += i;
               }
                   String Sum1 = String.valueOf(Sum); // convert to string
                   myTextField.setText(Sum1);
               }
               
               else {
                   
                    // multiply numbers from lower interval to upper interval
                   int Product = 1;
                   for (int i = lower; i <= upper; i++) { 
                        Product *= i;
               }
                   String Product1 = String.valueOf(Product); // convert to string
                   myTextField.setText(Product1);
           }
        }
           
        }
        
        catch (Exception e) {
            myTextField.setText("Incorrect Input"); // inform user about incorrect input
        }
    }//GEN-LAST:event_calculateSumOrProductActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        // TODO add your handling code here:
        System.exit(0); // Exit the application
    }//GEN-LAST:event_exitBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(U1A4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(U1A4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(U1A4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(U1A4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new U1A4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField lowerBound;
    private javax.swing.JButton minusBtn;
    private javax.swing.JComboBox<String> myComboBox;
    private javax.swing.JTextField myTextField;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JButton plusBtn;
    private javax.swing.JTextField upperBound;
    private javax.swing.JTextField userNum1;
    private javax.swing.JTextField userNum2;
    private javax.swing.JTextField userNum3;
    // End of variables declaration//GEN-END:variables
}
